---

- name: install system packages
  apt: pkg={{item}} state=present
  with_items: "{{system_packages}}"

- name: create frontend dir
  file: dest={{atlas_frontend_path}} owner={{atlas_webuser}} group={{atlas_webuser}} state=directory recurse=yes

- name: create vis-toolkit dir
  file: dest={{atlas_vistk_path}} owner={{atlas_webuser}} group={{atlas_webuser}} state=directory recurse=yes

- name: get frontend code
  git: repo={{atlas_frontend_git_repo}}
       dest={{atlas_frontend_path}}
       version={{atlas_frontend_git_version}}
       force=yes
       accept_hostkey=true
  sudo_user: "{{atlas_webuser}}"

- name: install sass
  gem: name=sass version=3.4.24 state=present

- name: install ember
  npm: name=ember-cli version=0.2.7 global=yes

- name: install grunt-cli
  npm: name=grunt-cli version=0.1.13 global=yes

- name: install bower
  npm: name=bower version=1.4.1 global=yes

- name: Install frontend packages based on package.json.
  npm: path={{atlas_frontend_path}}
  sudo_user: "{{atlas_webuser}}"

- name: bower unlink vis-toolkit
  shell: "bower unlink vis-toolkit"
  args:
      chdir: "{{atlas_frontend_path}}"
  sudo_user: "{{atlas_webuser}}"

- name: Install packages based on bower.json.
  shell: "bower install"
  args:
      chdir: "{{atlas_frontend_path}}"
  #bower: path={{atlas_frontend_path}}
  sudo_user: "{{atlas_webuser}}"

- name: get vis-toolkit code
  git: repo={{atlas_vistk_git_repo}}
       dest={{atlas_vistk_path}}
       version={{atlas_vistk_git_version}}
       accept_hostkey=true
  sudo_user: "{{atlas_webuser}}"

- name: bower link
  shell: "bower link"
  args:
      chdir: "{{atlas_vistk_path}}"
  sudo_user: "{{atlas_webuser}}"

- name: bower link vis-toolkit
  shell: "bower link vis-toolkit"
  args:
      chdir: "{{atlas_frontend_path}}"
  sudo_user: "{{atlas_webuser}}"

- name: set last_year variable
  replace:
    path: "{{atlas_frontend_path}}/app/variables/data-variables.js"
    regexp: '^\s*"last_year.*,$'
    replace: '"last_year": {{atlas_frontend_last_year}},'
  when: atlas_frontend_last_year is defined

- name: set first_year variable
  replace:
    path: "{{atlas_frontend_path}}/app/variables/data-variables.js"
    regexp: '^\s*"first_year.*,$'
    replace: '"first_year": {{atlas_frontend_first_year}},'
  when: atlas_frontend_first_year is defined

- name: set census_year variable
  replace:
    path: "{{atlas_frontend_path}}/app/variables/data-variables.js"
    regexp: '^\s*"census_year.*,$'
    replace: '"census_year": {{atlas_frontend_census_year}},'
  when: atlas_frontend_census_year is defined

- name: set agproduct year variables
  replace:
    path: "{{atlas_frontend_path}}/app/variables/data-variables.js"
    regexp: '^\s*"agproduct":.*,$'
    replace: '"agproduct": { "first_year": {{atlas_frontend_agproduct_first_year}}, "last_year": {{atlas_frontend_agproduct_last_year}} },'
  when: (atlas_frontend_agproduct_first_year is defined) and (atlas_frontend_agproduct_last_year is defined)

- name: set agcensus year variables
  replace:
    path: "{{atlas_frontend_path}}/app/variables/data-variables.js"
    regexp: '^\s*"agcensus":.*$'
    replace: '"agcensus": { "first_year": {{atlas_frontend_agcensus_first_year}}, "last_year": {{atlas_frontend_agcensus_last_year}} },'
  when: (atlas_frontend_agcensus_first_year is defined) and (atlas_frontend_agcensus_last_year is defined)

- name: copy over custom translations file
  copy:
    src: "translations/"
    dest: "{{atlas_frontend_path}}/app/locales/"
    owner: "{{atlas_webuser}}"
  when: (atlas_update_custom_translations is defined) and (atlas_update_custom_translations == True)

- name: ember build
  shell: "cd {{atlas_frontend_path}}; ember build --environment=production"
  args:
      chdir: "{{atlas_frontend_path}}"
  environment: "{{atlas_ember_environment}}"
  sudo_user: "{{atlas_webuser}}"
